spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db_dev
    username: postgres
    password: postgres
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: DEBUG
    com.towsoth.edu: DEBUG
    org.springframework.security: DEBUG
