export type AppSectionId =
  | "dashboard"
  | "institutions"
  | "plans"
  | "roles"
  | "users"
  | "ai-control"
  | "compliance"
  | "billing"
  | "security"
  | "analytics"
  | "config"
  | "governance"
  | "logs"
  | "emergency";
