import type { FilterConfig } from '../../components/filters/FilterBar';
import type { AssessmentItem } from '../../types/operations';

export const getAssessmentItems = (): AssessmentItem[] => [
  {
    id: 'ASS001',
    title: 'Midterm Examination - Data Structures',
    type: 'Written Exam',
    subject: 'CS-301',
    batch: 'CS-A3, CS-B3',
    date: '2025-01-15',
    dueDate: '2025-01-15',
    duration: '120 min',
    totalMarks: 100,
    questions: 42,
    status: 'Published',
    gradingState: 'Pending grading',
    completed: 115,
    total: 118,
  },
  {
    id: 'ASS002',
    title: 'Quiz 3 - Operating Systems',
    type: 'MCQ Quiz',
    subject: 'CS-302',
    batch: 'CS-A3',
    date: '2025-01-10',
    dueDate: '2025-01-10',
    duration: '30 min',
    totalMarks: 20,
    questions: 15,
    status: 'Completed',
    gradingState: 'Fully graded',
    completed: 58,
    total: 58,
  },
  {
    id: 'ASS003',
    title: 'Assignment - Database Design',
    type: 'Assignment',
    subject: 'CS-303',
    batch: 'CS-A3',
    date: '2025-01-20',
    dueDate: '2025-01-20',
    duration: 'N/A',
    totalMarks: 50,
    questions: 5,
    status: 'Draft',
    gradingState: 'Pending grading',
    completed: 0,
    total: 58,
  },
  {
    id: 'ASS004',
    title: 'Final Examination - Computer Networks',
    type: 'Comprehensive Exam',
    subject: 'CS-304',
    batch: 'CS-A3, CS-B3, CS-C3',
    date: '2025-02-05',
    dueDate: '2025-02-05',
    duration: '180 min',
    totalMarks: 100,
    questions: 50,
    status: 'Published',
    gradingState: 'Partially graded',
    completed: 98,
    total: 120,
  },
  {
    id: 'ASS005',
    title: 'Lab Practical - Machine Learning',
    type: 'Practical Test',
    subject: 'CS-305',
    batch: 'CS-A3',
    date: '2025-01-25',
    dueDate: '2025-01-25',
    duration: '90 min',
    totalMarks: 75,
    questions: 3,
    status: 'Draft',
    gradingState: 'Pending grading',
    completed: 0,
    total: 58,
  },
  {
    id: 'ASS006',
    title: 'Programming Assignment - Algorithms',
    type: 'Assignment',
    subject: 'CS-301',
    batch: 'CS-A3',
    date: '2025-01-08',
    dueDate: '2025-01-08',
    duration: 'N/A',
    totalMarks: 40,
    questions: 3,
    status: 'Completed',
    gradingState: 'Fully graded',
    completed: 58,
    total: 58,
  },
];

export const getAssessmentFilterConfig = (): FilterConfig[] => [
  {
    id: 'subject',
    label: 'Subject',
    type: 'dropdown',
    options: [
      { value: 'CS-301', label: 'CS-301' },
      { value: 'CS-302', label: 'CS-302' },
      { value: 'CS-303', label: 'CS-303' },
      { value: 'CS-304', label: 'CS-304' },
      { value: 'CS-305', label: 'CS-305' },
    ],
  },
  {
    id: 'assessmentType',
    label: 'Type',
    type: 'multiselect',
    options: [
      { value: 'Written Exam', label: 'Written Exam' },
      { value: 'MCQ Quiz', label: 'MCQ Quiz' },
      { value: 'Assignment', label: 'Assignment' },
      { value: 'Practical Test', label: 'Practical Test' },
      { value: 'Comprehensive Exam', label: 'Comprehensive Exam' },
    ],
  },
  {
    id: 'status',
    label: 'Status',
    type: 'multiselect',
    options: [
      { value: 'Published', label: 'Published' },
      { value: 'Draft', label: 'Draft' },
      { value: 'Completed', label: 'Completed' },
    ],
  },
  {
    id: 'schedule',
    label: 'Schedule',
    type: 'dropdown',
    options: [
      { value: 'past', label: 'Past' },
      { value: 'today', label: 'Today' },
      { value: 'upcoming', label: 'Upcoming' },
    ],
  },
  {
    id: 'progress',
    label: 'Progress',
    type: 'dropdown',
    options: [
      { value: 'not-started', label: 'Not Started (0%)' },
      { value: 'in-progress', label: 'In Progress' },
      { value: 'fully-submitted', label: 'Fully Submitted' },
    ],
  },
  {
    id: 'search',
    label: 'Search',
    type: 'search',
    placeholder: 'Search assessments, subjects, or types...',
  },
];
